### ISSUE TITLE
Meeting Minutes

### ISSUE THREAD

**Issue by larahabashy** [UBC-MDS/DSCI_532_Group15_wine#9]
Milestone 1 App Sketch meeting minutes:

- Reminder to add proposal parts to the proposal docs [here](https://docs.google.com/document/d/1CpRwSW8MofzDnt8gxxNL9aEn8MiR8sNwWU8X3A5p7ao/edit#heading=h.rpc2cqkh8k3)
- @wiwang to complete section 2
- @MattTPin to write app description (paragraph)
- @MattTPin to write README description (2-3 sentences)
- Lara to beautify sketch
- Zoom [meeting](https://github.com/UBC-MDS/DSCI_532_Group15_wine/issues/10) Saturday at 10:30

**Comment by MattTPin** [comment]
Meeting occurred successfully
